spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/products/**
        - id: category
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/categories/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
