spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/products/**
        - id: category
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/categories/**



