---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: "product_delete"
        uri: "http://localhost:8089"
        predicates:
        - "Path=/api/v1/products/{productId}"
        - "Method=DELETE"
        metadata:
          microservice: "product"
      - id: "product_add_category"
        uri: "http://localhost:8089"
        predicates:
        - "Path=/api/v1/products/categories"
        - "Method=POST"
        metadata:
          microservice: "product"
      - id: "category_add"
        uri: "http://localhost:8088"
        predicates:
        - "Path=/api/v1/categories"
        - "Method=POST"
        metadata:
          microservice: "category"
      - id: "category_get_all"
        uri: "http://localhost:8088"
        predicates:
        - "Path=/api/v1/categories"
        - "Method=GET"
        metadata:
          microservice: "category"
